import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en'); // 'en' for English, 'ar' for Arabic

  const toggleLanguage = () => {
    setLanguage((prevLang) => (prevLang === 'en' ? 'ar' : 'en'));
  };

  const translations = {
    en: {
      dashboard: 'Dashboard',
      clients: 'Clients',
      messages: 'Messages',
      logout: 'Logout',
      login: 'Login',
      welcome: 'Welcome',
      username: 'Username',
      password: 'Password',
      all_rights_reserved: 'All rights reserved',
      dashboard_overview: 'Overview of the system',
      services: 'Services',
      manage_services: 'Manage Services',
      manage_services_desc: 'Manage and update provided services',
      products: 'Products',
      manage_products: 'Manage Products',
      projects: 'Projects',
      manage_projects: 'Manage Projects',
      testimonials: 'Testimonials',
      manage_testimonials: 'Manage Testimonials',
      customer_messages: 'Customer Messages',
      total_services: 'Total Services',
      active_service: 'Active Service',
      available_product: 'Available Product',
      completed_project: 'Completed Project',
      new_message: 'New Message',
      monthly_revenue: 'Monthly Revenue',
      currency: 'SAR',
      this_month: 'This Month',
      active_user: 'Active User',
      active_users: 'Active Users',
      welcome_dashboard: 'Welcome to the Dashboard',
      ajwan_overview: 'Overview of Ajwan website performance',
      recent_activities: 'Recent Activities',
      new_service_added: 'New service added',
      product_updated: 'Product updated',
      new_message_from_client: 'New message from client',
      project_completed: 'Project completed',
      five_minutes_ago: '5 minutes ago',
      fifteen_minutes_ago: '15 minutes ago',
      thirty_minutes_ago: '30 minutes ago',
      one_hour_ago: '1 hour ago',
      upcoming_tasks: 'Upcoming Tasks',
      review_new_project: 'Review new project',
      update_website_content: 'Update website content',
      team_meeting: 'Team meeting',
      prepare_monthly_report: 'Prepare monthly report',
      today: 'Today',
      tomorrow: 'Tomorrow',
      wednesday: 'Wednesday',
      friday: 'Friday',
      high: 'High',
      medium: 'Medium',
      normal: 'Normal',
      low: 'Low',
      add_new_service: 'Add New Service',
      services_list: 'Services List',
      search_services: 'Search Services...', 
      service_name: 'Service Name',
      category: 'Category',
      price: 'Price',
      status: 'Status',
      created_at: 'Created At',
      actions: 'Actions',
      development: 'Development',
      marketing: 'Marketing',
      design: 'Design',
      active: 'Active',
      inactive: 'Inactive',
      edit_service: 'Edit Service',
      enter_service_name: 'Enter service name',
      enter_service_category: 'Enter service category',
      enter_service_price: 'Enter service price',
      description: 'Description',
      enter_service_description: 'Enter service description',
      cancel: 'Cancel',
      save: 'Save',
      update: 'Update',
      website_development: 'Website Development',
      website_development_desc: 'Design and develop professional and responsive websites',
      digital_marketing: 'Digital Marketing',
      digital_marketing_desc: 'Social media marketing and advertising services',
      visual_identity_design: 'Visual Identity Design',
      visual_identity_design_desc: 'Designing logos and visual identities for companies',
      manage_messages: 'Manage Messages',
      customer_messages_and_inquiries: 'Customer messages and inquiries',
      unread: 'Unread',
      urgent: 'Urgent',
      inbox: 'Inbox',
      search_messages: 'Search Messages...', 
      all_messages: 'All Messages',
      read: 'Read',
      replied: 'Replied',
      message_details: 'Message Details',
      received_at: 'Received At',
      replied_at: 'Replied At',
      close: 'Close',
      reply: 'Reply',
      reply_to_message: 'Reply to Message',
      your_reply: 'Your Reply',
      type_your_reply_here: 'Type your reply here...', 
      send_reply: 'Send Reply',
      no_messages_match_search: 'No messages match the search',
      inquiry_development_services: 'Inquiry about development services',
      inquiry_development_services_content: 'I would like to get a quote for developing a website for my company. The website will display services and products with the ability to communicate with customers.',
      technical_support_request: 'Technical support request',
      technical_support_request_content: 'I am facing a problem with the system you developed for us. I cannot access the control panel. Please help as soon as possible.',
      thank_you_and_appreciation: 'Thank you and appreciation',
      thank_you_and_appreciation_content: 'Thank you for the excellent service and professional dealing. The project was delivered on time and with high quality. I look forward to working with you again.',
      admin: 'Admin',
      manage_products_desc: 'Manage and update products',
      product_name: 'Product Name',
      enter_product_name: 'Enter product name',
      enter_product_category: 'Enter product category',
      enter_product_price: 'Enter product price',
      add_new_product: 'Add New Product',
      edit_product: 'Edit Product',
      products_list: 'Products List',
      search_products: 'Search Products...',
      specifications: 'Specifications',
      specifications_count: 'specifications',
      content_management_system: 'Content Management System',
      content_management_system_desc: 'Professional content management system',
      mobile_application: 'Mobile Application',
      mobile_application_desc: 'Cross-platform mobile application',
      software: 'Software',
      applications: 'Applications',
      language: 'Language',
      arabic_and_english: 'Arabic and English',
      database: 'Database',
      platforms: 'Platforms',
      technology: 'Technology',
      product_images: 'Product Images',
      product_video: 'Product Video',
      service_ajwains: 'Related Services',
      enter_related_services_comma_separated: 'Enter related services (comma separated)',
      availability: 'Availability',
      available: 'Available',
      not_available: 'Not Available',
      service_description: 'Service Description',
      service_title: 'Service Title',
      enter_service_title: 'Enter service title',
      service_images: 'Service Images',
      service_icon: 'Service Icon',
      product_ajwans: 'Related Products',
      enter_related_products_comma_separated: 'Enter related products (comma separated)',
      service_items: 'Service Items',
      enter_service_items_comma_separated: 'Enter service items (comma separated)',
      manage_users: 'Manage Users',
      manage_users_desc: 'Manage system users and permissions',
      users_list: 'Users List',
      search_users: 'Search Users...',
      add_new_user: 'Add New User',
      edit_user: 'Edit User',
      save_user: 'Save User',
      enter_username: 'Enter username',
      enter_password: 'Enter password',
      role: 'Role',
      user: 'User',
      users: 'Users',
      manage_service_items: 'Manage Service Items',
      manage_service_items_desc: 'Manage individual service items',
      service_items_list: 'Service Items List',
      search_service_items: 'Search Service Items...',
      add_new_service_item: 'Add New Service Item',
      edit_service_item: 'Edit Service Item',
      save_service_item: 'Save Service Item',
      title: 'Title',
      enter_service_item_title: 'Enter service item title',
      enter_service_item_description: 'Enter service item description',
      image_items: 'Image Items',
      service_ajwain: 'Related Service',
      enter_related_service: 'Enter related service',
      service_item_title_1: 'Web Development',
      service_item_description_1: 'Professional web development services',
      service_item_title_2: 'Mobile App Development',
      service_item_description_2: 'Cross-platform mobile application development',
      
 
 

    },
    ar: {
      dashboard: 'لوحة القيادة',
      clients: 'العملاء',
      messages: 'الرسائل',
      logout: 'تسجيل الخروج',
      login: 'تسجيل الدخول',
      welcome: 'أهلاً بك',
      username: 'اسم المستخدم',
      password: 'كلمة المرور',
      all_rights_reserved: 'جميع الحقوق محفوظة',
      dashboard_overview: 'نظرة عامة على النظام',
      services: 'الخدمات',
      manage_services: 'إدارة الخدمات',
      manage_services_desc: 'إدارة وتحديث الخدمات المقدمة',
      products: 'المنتجات',
      manage_products: 'إدارة المنتجات',
      projects: 'المشاريع',
      manage_projects: 'إدارة المشاريع',
      testimonials: 'التوصيات',
      manage_testimonials: 'إدارة آراء العملاء',
      customer_messages: 'رسائل العملاء',
      total_services: 'إجمالي الخدمات',
      active_service: 'خدمة نشطة',
      available_product: 'منتج متاح',
      completed_project: 'مشروع مكتمل',
      new_message: 'رسالة جديدة',
      monthly_revenue: 'الإيرادات الشهرية',
      currency: 'ر.س',
      this_month: 'هذا الشهر',
      active_user: 'مستخدم نشط',
      active_users: 'المستخدمون النشطون',
      welcome_dashboard: 'مرحباً بك في لوحة التحكم',
      ajwan_overview: 'نظرة عامة على أداء موقع Ajwan',
      recent_activities: 'الأنشطة الأخيرة',
      new_service_added: 'تم إضافة خدمة جديدة',
      product_updated: 'تم تحديث منتج',
      new_message_from_client: 'رسالة جديدة من العميل',
      project_completed: 'تم إكمال مشروع',
      five_minutes_ago: 'منذ 5 دقائق',
      fifteen_minutes_ago: 'منذ 15 دقيقة',
      thirty_minutes_ago: 'منذ 30 دقيقة',
      one_hour_ago: 'منذ ساعة',
      upcoming_tasks: 'المهام القادمة',
      review_new_project: 'مراجعة المشروع الجديد',
      update_website_content: 'تحديث محتوى الموقع',
      team_meeting: 'اجتماع مع الفريق',
      prepare_monthly_report: 'إعداد التقرير الشهري',
      today: 'اليوم',
      tomorrow: 'غداً',
      wednesday: 'الأربعاء',
      friday: 'الجمعة',
      high: 'عالية',
      medium: 'متوسطة',
      normal: 'عادية',
      low: 'منخفضة',
      add_new_service: 'إضافة خدمة جديدة',
      services_list: 'قائمة الخدمات',
      search_services: 'البحث في الخدمات...', 
      service_name: 'اسم الخدمة',
      category: 'الفئة',
      price: 'السعر',
      status: 'الحالة',
      created_at: 'تاريخ الإنشاء',
      actions: 'الإجراءات',
      development: 'تطوير',
      marketing: 'تسويق',
      design: 'تصميم',
      active: 'نشط',
      inactive: 'غير نشط',
      edit_service: 'تعديل الخدمة',
      enter_service_name: 'أدخل اسم الخدمة',
      enter_service_category: 'أدخل فئة الخدمة',
      enter_service_price: 'أدخل سعر الخدمة',
      description: 'الوصف',
      enter_service_description: 'أدخل وصف الخدمة',
      cancel: 'إلغاء',
      save: 'حفظ',
      update: 'تحديث',
      website_development: 'تطوير المواقع الإلكترونية',
      website_development_desc: 'تصميم وتطوير مواقع إلكترونية احترافية ومتجاوبة',
      digital_marketing: 'التسويق الرقمي',
      digital_marketing_desc: 'خدمات التسويق عبر وسائل التواصل الاجتماعي والإعلانات',
      visual_identity_design: 'تصميم الهوية البصرية',
      visual_identity_design_desc: 'تصميم الشعارات والهوية البصرية للشركات',
      manage_messages: 'إدارة الرسائل',
      customer_messages_and_inquiries: 'رسائل العملاء والاستفسارات',
      unread: 'غير مقروءة',
      urgent: 'عاجلة',
      inbox: 'صندوق الرسائل',
      search_messages: 'البحث في الرسائل...', 
      all_messages: 'جميع الرسائل',
      read: 'مقروءة',
      replied: 'تم الرد عليها',
      message_details: 'تفاصيل الرسالة',
      received_at: 'تلقى في',
      replied_at: 'تم الرد في',
      close: 'إغلاق',
      reply: 'رد',
      reply_to_message: 'الرد على الرسالة',
      your_reply: 'ردك',
      type_your_reply_here: 'اكتب ردك هنا...', 
      send_reply: 'إرسال الرد',
      no_messages_match_search: 'لا توجد رسائل تطابق البحث',
      inquiry_development_services: 'استفسار عن خدمات التطوير',
      inquiry_development_services_content: 'أرغب في الحصول على عرض سعر لتطوير موقع إلكتروني لشركتي. الموقع سيكون لعرض الخدمات والمنتجات مع إمكانية التواصل مع العملاء.',
      technical_support_request: 'طلب دعم تقني',
      technical_support_request_content: 'أواجه مشكلة في النظام الذي طورتموه لنا. لا أستطيع الوصول إلى لوحة التحكم. أرجو المساعدة في أسرع وقت ممكن.',
      thank_you_and_appreciation: 'شكر وتقدير',
      thank_you_and_appreciation_content: 'أشكركم على الخدمة الممتازة والتعامل الراقي. المشروع تم تسليمه في الوقت المحدد وبجودة عالية. أتطلع للتعامل معكم مرة أخرى.',
      admin: 'المدير',
      manage_products_desc: 'إدارة وتحديث المنتجات',
      product_name: 'اسم المنتج',
      enter_product_name: 'أدخل اسم المنتج',
      enter_product_category: 'أدخل فئة المنتج',
      enter_product_price: 'أدخل سعر المنتج',
      add_new_product: 'إضافة منتج جديد',
      edit_product: 'تعديل المنتج',
      products_list: 'قائمة المنتجات',
      search_products: 'البحث في المنتجات...',
      specifications: 'المواصفات',
      specifications_count: 'مواصفة',
      content_management_system: 'نظام إدارة المحتوى',
      content_management_system_desc: 'نظام إدارة محتوى احترافي',
      mobile_application: 'تطبيق الهاتف المحمول',
      mobile_application_desc: 'تطبيق هاتف محمول متعدد المنصات',
      software: 'برمجيات',
      applications: 'تطبيقات',
      language: 'اللغة',
      arabic_and_english: 'العربية والإنجليزية',
      database: 'قاعدة البيانات',
      platforms: 'المنصات',
      technology: 'التقنية',
      product_images: 'صور المنتج',
      product_video: 'فيديو المنتج',
      service_ajwains: 'الخدمات المرتبطة',
      enter_related_services_comma_separated: 'أدخل الخدمات المرتبطة (مفصولة بفاصلة)',
      availability: 'التوفر',
      available: 'متوفر',
      not_available: 'غير متوفر',
      service_description: 'وصف الخدمة',
      service_title: 'عنوان الخدمة',
      enter_service_title: 'أدخل عنوان الخدمة',
      service_images: 'صور الخدمة',
      service_icon: 'أيقونة الخدمة',
      product_ajwans: 'المنتجات المرتبطة',
      enter_related_products_comma_separated: 'أدخل المنتجات المرتبطة (مفصولة بفاصلة)',
      service_items: 'عناصر الخدمة',
      enter_service_items_comma_separated: 'أدخل عناصر الخدمة (مفصولة بفاصلة)',
      manage_users: 'إدارة المستخدمين',
      manage_users_desc: 'إدارة مستخدمي النظام والصلاحيات',
      users_list: 'قائمة المستخدمين',
      search_users: 'البحث في المستخدمين...',
      add_new_user: 'إضافة مستخدم جديد',
      edit_user: 'تعديل المستخدم',
      save_user: 'حفظ المستخدم',
      enter_username: 'أدخل اسم المستخدم',
      enter_password: 'أدخل كلمة المرور',
      role: 'الدور',
      user: 'مستخدم',
      users: 'المستخدمون',
      manage_service_items: 'إدارة عناصر الخدمة',
      manage_service_items_desc: 'إدارة عناصر الخدمة الفردية',
      service_items_list: 'قائمة عناصر الخدمة',
      search_service_items: 'البحث في عناصر الخدمة...',
      add_new_service_item: 'إضافة عنصر خدمة جديد',
      edit_service_item: 'تعديل عنصر الخدمة',
      save_service_item: 'حفظ عنصر الخدمة',
      title: 'العنوان',
      enter_service_item_title: 'أدخل عنوان عنصر الخدمة',
      enter_service_item_description: 'أدخل وصف عنصر الخدمة',
      image_items: 'صور العناصر',
      service_ajwain: 'الخدمة المرتبطة',
      enter_related_service: 'أدخل الخدمة المرتبطة',
      service_item_title_1: 'تطوير المواقع',
      service_item_description_1: 'خدمات تطوير المواقع الاحترافية',
      service_item_title_2: 'تطوير تطبيقات الهاتف',
      service_item_description_2: 'تطوير تطبيقات الهاتف متعددة المنصات',
      
 


    },
  };

  const t = (key) => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);


